### ISSUE TITLE
3.10.16 not recognized as latest 3.10 version

### ISSUE THREAD

**Issue by neunkasulle** [glyph/MOPUp#398] opened 2024-12-04 20:40 UTC
It points to 3.10.11 instead:
```
~ via 🐍 v3.10.15 took 6s
➜ mopup
this version: 3.10.15; new version: 3.10.11
update not needed from https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg

❯ pip list
Package            Version
------------------ ----------
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.4.0
click              8.1.7
cryptography       43.0.3
distlib            0.3.9
filelock           3.16.1
html5lib           1.1
hyperlink          21.0.0
idna               3.10
markdown-it-py     3.0.0
mdurl              0.1.2
MOPUp              2024.8.9.1
nvidia-pyindex     1.0.9
packaging          24.2
pip                24.3.1
pipenv             2024.4.0
platformdirs       4.3.6
pycparser          2.22
Pygments           2.18.0
pyOpenSSL          24.2.1
requests           2.32.3
rich               13.9.4
setuptools         75.6.0
six                1.17.0
types-click        7.1.8
typing_extensions  4.12.2
urllib3            2.2.3
virtualenv         20.27.1
webencodings       0.5.1
wheel              0.45.0


```

**Comment by glyph** [comment] 2024-12-05 01:32
This is a duplicate of #386 .  The problem here is that upstream python.org does not produce binary installers for these security releases, so in order for MOPUp to detect these, we would need to add a whole infrastructure for building and signing binaries.  I'm open to PRs for this, but MOPUp as it is is a micro-tool, and invoking Python.org's whole build infrastructure is a major project.

**Closed as not planned by glyph** 2024-12-05 01:32 UTC
